/* eslint-disable react/no-unescaped-entities */
import { createClient } from 'contentful';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { About, Hero } from '../components';
import Contact from '../components/Contact';
import FeaturedProjects from '../components/FeaturedProjects';
import Jobs from '../components/Jobs';
import { Project } from '../types';
import { aboutData, homeData, jobsData } from '../utils/constants';

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID || 'prik3ds8tbo9',
  accessToken:
    process.env.CONTENTFUL_ACCESS_KEY ||
    'CvbixxyBg1MNPozWW3ToZvhue_k05f31yfppDEgBH94',
});

export const getStaticProps: GetStaticProps = async () => {
  const res = await client.getEntries({ content_type: 'project' });
  const projects = res.items.map(item => item.fields);

  return {
    props: { projects },
  };
};

const Home: NextPage<{ projects: Project[] }> = ({ projects }) => {
  console.log(projects);

  return (
    <div>
      <Head>
        <title>Son Nguyen | Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero {...homeData} />
      <About {...aboutData} />
      <Jobs jobs={jobsData} />
      <FeaturedProjects projects={projects} />
      <Contact />
    </div>
  );
};

export default Home;
