/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next';
import Head from 'next/head';
import { About, Hero } from '../components';
import { aboutData, homeData } from '../utils/constants';

// const client = createClient({
//   space: process.env.CONTENTFUL_SPACE_ID || '',
//   accessToken: process.env.CONTENTFUL_ACCESS_KEY || '',
// });

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Son Nguyen | Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero {...homeData} />
      <About {...aboutData} />
    </div>
  );
};

export default Home;
